/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewMain;

import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Task;


public class designViewMainV3 extends javax.swing.JFrame {

    private TaskController controller;
    private viewFormAddTask FormAddTask;
    
    
    /**
     * Creates new form designViewMainV3
     */
    public designViewMainV3() {
        initComponents();
        createInfoTask(); // Gọi hàm tạo task khi khởi tạo
        updateProgressInfo(); // Cập nhật progress bar
        setLocationRelativeTo(null);// hien thi giua man hinh
    }
    
   
//     * HÀM REFRESCH CHỈ DÙNG TRONG CỬA SỔ NÀY
     
    private void refreshMainWindow() {
        createInfoTask();        // Load lại danh sách task
        updateProgressInfo();    // Cập nhật progress bar
        System.out.println("Đã refresh cửa sổ chính!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        displayAddTask_JLB = new javax.swing.JPanel();
        addTask_JLB = new javax.swing.JPanel();
        addTask_JLP = new javax.swing.JLabel();
        ADD_TASK_JBT = new javax.swing.JButton();
        displayCRUD_JLP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display_JLP = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();// phần thêm lịch 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        displayAddTask_JLB.setBackground(new java.awt.Color(204, 255, 255));

        addTask_JLB.setBackground(new java.awt.Color(234, 255, 255));
        addTask_JLB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÊM TASK CỦA BẠN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(153, 153, 153))); // NOI18N

        addTask_JLP.setBackground(new java.awt.Color(204, 255, 255));
        addTask_JLP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        addTask_JLP.setLabelFor(ADD_TASK_JBT);

        ADD_TASK_JBT.setBackground(new java.awt.Color(204, 255, 255));
        ADD_TASK_JBT.setForeground(new java.awt.Color(153, 153, 153));
        ADD_TASK_JBT.setText("ADD TASK");
        ADD_TASK_JBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_TASK_JBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTask_JLBLayout = new javax.swing.GroupLayout(addTask_JLB);
        addTask_JLB.setLayout(addTask_JLBLayout);
        addTask_JLBLayout.setHorizontalGroup(
            addTask_JLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTask_JLBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTask_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTask_JLBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ADD_TASK_JBT)
                .addGap(225, 225, 225))
        );
        addTask_JLBLayout.setVerticalGroup(
            addTask_JLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTask_JLBLayout.createSequentialGroup()
                .addComponent(addTask_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ADD_TASK_JBT)
                .addGap(18, 18, 18))
        );

        displayCRUD_JLP.setBackground(new java.awt.Color(235, 255, 255));
        displayCRUD_JLP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TASK HIỆN TẠI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(153, 153, 153))); // NOI18N

        // QUAN TRỌNG: Thiết lập layout cho display_JLP - BoxLayout theo chiều dọc (từ viewV3)
        display_JLP.setBackground(new java.awt.Color(234, 255, 255));
        display_JLP.setLayout(new javax.swing.BoxLayout(display_JLP, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportView(display_JLP);
        
        // Thiết lập auto scroll (từ viewV3)
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        javax.swing.GroupLayout displayCRUD_JLPLayout = new javax.swing.GroupLayout(displayCRUD_JLP);
        displayCRUD_JLP.setLayout(displayCRUD_JLPLayout);
        displayCRUD_JLPLayout.setHorizontalGroup(
            displayCRUD_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        displayCRUD_JLPLayout.setVerticalGroup(
            displayCRUD_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayCRUD_JLPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout displayAddTask_JLBLayout = new javax.swing.GroupLayout(displayAddTask_JLB);
        displayAddTask_JLB.setLayout(displayAddTask_JLBLayout);
        displayAddTask_JLBLayout.setHorizontalGroup(
            displayAddTask_JLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayCRUD_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addTask_JLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        displayAddTask_JLBLayout.setVerticalGroup(
            displayAddTask_JLBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayAddTask_JLBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addTask_JLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayCRUD_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(234, 255, 255));

        jPanel7.setBackground(new java.awt.Color(234, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(235, 255, 255), new java.awt.Color(236, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("TO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("DAY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(235, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(235, 255, 255), new java.awt.Color(234, 255, 255), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));

        jProgressBar1.setBackground(new java.awt.Color(204, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(235, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("0/0 Task");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(235, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayAddTask_JLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayAddTask_JLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void ADD_TASK_JBTActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Mở form thêm task mới với callback refresh (từ viewV3)
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFormAddTask(new Runnable() {
                    @Override
                    public void run() {
                        refreshMainWindow(); // Refresh khi thêm task thành công
                    }
                }).setVisible(true);
            }
        });
    }                                            

    private void detailTask_JBTActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Có thể để trống hoặc hiển thị thông báo
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một task để xem chi tiết");
    }                                              

                                                 
    
    
    // HÀM TẠO INFO TASK VỚI CHECKBOX
    public void createInfoTask() {
        controller = new TaskController();
        List<Task> list = controller.getAllTasks();
        
        // Xóa các component cũ trước khi thêm mới
        display_JLP.removeAll();
        
        for (int i = 0; i < list.size(); i++) {
            // Tạo components MỚI cho mỗi task
            JPanel infoTask_JLP = new JPanel();
            JCheckBox completeCheckBox = new JCheckBox(); // CHECKBOX
            JLabel describeTask_JLP = new JLabel();
            JButton detailTask_JBT = new JButton();
            JButton editTask_JBT = new JButton();
            JButton deleteTask_JBT = new JButton();
            
            // Lưu taskId để sử dụng trong event listeners
            final int taskId = list.get(i).getId();
            final String taskTitle = list.get(i).getTitle();
            final String taskStatus = list.get(i).getStatus();
            
            // Thiết lập thuộc tính
            infoTask_JLP.setBackground(new java.awt.Color(204, 255, 255));
            infoTask_JLP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 255, 255), new java.awt.Color(204, 255, 255)));
            infoTask_JLP.setForeground(new java.awt.Color(204, 204, 204));
            infoTask_JLP.setName("infoTask_JLP" + taskId);
            
            // THIẾT LẬP CHECKBOX
            completeCheckBox.setBackground(new Color(204, 204, 255));
            completeCheckBox.setSelected("Completed".equals(taskStatus) || "Đã hoàn thành".equals(taskStatus));
            
            describeTask_JLP.setBackground(new Color(204, 204, 255));
            describeTask_JLP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // Font đẹp hơn
            
            // NẾU TASK ĐÃ HOÀN THÀNH, GẠCH NGANG CHỮ
            if ("Completed".equals(taskStatus) || "Đã hoàn thành".equals(taskStatus)) {
                describeTask_JLP.setFont(describeTask_JLP.getFont().deriveFont(Font.PLAIN));
                describeTask_JLP.setForeground(Color.GRAY);
                describeTask_JLP.setText("<html><strike>" + taskTitle + "</strike></html>");
            } else {
                describeTask_JLP.setText(taskTitle);
            }
            
            detailTask_JBT.setBackground(new Color(153, 153, 153));
            detailTask_JBT.setIcon(loadIcon("iConView.png"));
            detailTask_JBT.setToolTipText("Xem chi tiết task");
            detailTask_JBT.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    detailTask_JBTActionPerformed(evt, taskId);
                }
            });
            
            editTask_JBT.setBackground(new Color(153, 153, 153));
            editTask_JBT.setIcon(loadIcon("iConEdit.png"));
            editTask_JBT.setToolTipText("Sửa task");
            editTask_JBT.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    editTask_JBTActionPerformed(evt, taskId);
                }
            });
            
            deleteTask_JBT.setBackground(new Color(153, 153, 153));
            deleteTask_JBT.setIcon(loadIcon("iConDelete.png"));
            deleteTask_JBT.setToolTipText("Xóa task");
            deleteTask_JBT.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    deleteTask_JBTActionPerformed(evt, taskId);
                }
            });

            // SỰ KIỆN CHO CHECKBOX
            completeCheckBox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    completeCheckBoxActionPerformed(evt, taskId, describeTask_JLP, completeCheckBox.isSelected());
                }
            });

            // Thiết lập layout cho infoTask_JLP - ĐÃ THÊM CHECKBOX
            javax.swing.GroupLayout infoTask_JLPLayout = new javax.swing.GroupLayout(infoTask_JLP);
            infoTask_JLP.setLayout(infoTask_JLPLayout);
            infoTask_JLPLayout.setHorizontalGroup(
                infoTask_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoTask_JLPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(completeCheckBox)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(describeTask_JLP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailTask_JBT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(editTask_JBT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(deleteTask_JBT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15))
            );
            infoTask_JLPLayout.setVerticalGroup(
                infoTask_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoTask_JLPLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(infoTask_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(infoTask_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(completeCheckBox)
                            .addComponent(describeTask_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(infoTask_JLPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailTask_JBT)
                            .addComponent(editTask_JBT)
                            .addComponent(deleteTask_JBT)))
                    .addContainerGap())
            );

            // THÊM panel task vào display_JLP
            display_JLP.add(infoTask_JLP);
            
            // Thêm khoảng cách giữa các task
            display_JLP.add(Box.createVerticalStrut(5));
        }
        
        // Refresh layout sau khi thêm components
        display_JLP.revalidate();
        display_JLP.repaint();
    }
    
// HÀM REFRESH DANH SÁCH TASK
    private void refreshTaskList() {
        createInfoTask();
    }
    
    // CẬP NHẬT THÔNG TIN TIẾN ĐỘ
    private void updateProgressInfo() {
        controller = new TaskController();
        List<Task> allTasks = controller.getAllTasks();
        
        int totalTasks = allTasks.size();
        int completedTasks = 0;
        
        for (Task task : allTasks) {
            if ("Đã hoàn thành".equals(task.getStatus()) ) {
                completedTasks++;
            }
        }
        
        // Cập nhật label
        jLabel4.setText(completedTasks + "/" + totalTasks + " Task");
        
        // Cập nhật progress bar
        if (totalTasks > 0) {
            int progress = (int) ((completedTasks * 100) / totalTasks);
            jProgressBar1.setValue(progress);
        } else {
            jProgressBar1.setValue(0);
        }
    }
    
    // PHƯƠNG THỨC LOAD ICON TỪ RESOURCES (CẢI TIẾN)
    private ImageIcon loadIcon(String fileName) {
        try {
            java.net.URL imgURL = getClass().getResource("/view/img/" + fileName);
            if (imgURL != null) {
                return new ImageIcon(imgURL);
            } else {
                // Fallback: tạo icon đơn giản nếu không tìm thấy file
                System.err.println("Không tìm thấy icon: " + fileName);
                return createDefaultIcon();
            }
        } catch (Exception e) {
            e.printStackTrace();
            return createDefaultIcon();
        }
    }
    
    // TẠO ICON MẶC ĐỊNH NẾU KHÔNG TÌM THẤY FILE
    private ImageIcon createDefaultIcon() {
        // Tạo một icon đơn giản màu xám
        java.awt.image.BufferedImage image = new java.awt.image.BufferedImage(16, 16, java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D g2d = image.createGraphics();
        g2d.setColor(Color.GRAY);
        g2d.fillRect(0, 0, 16, 16);
        g2d.dispose();
        return new ImageIcon(image);
    }
    
// PHƯƠNG THỨC XỬ LÝ SỰ KIỆN CHECKBOX
   private void completeCheckBoxActionPerformed(ActionEvent evt, int taskId, JLabel describeLabel, boolean isCompleted) {
        String newStatus = isCompleted ? "Đã hoàn thành" : "Chưa hoàn thành";
        if (controller.updateTaskStatus(taskId, newStatus)) {
            // Thay đổi hiển thị của label
            if (isCompleted) {
                describeLabel.setFont(describeLabel.getFont().deriveFont(Font.PLAIN));
                describeLabel.setForeground(Color.GRAY);
                String plainText = describeLabel.getText().replaceAll("<.*?>", "");
                describeLabel.setText("<html><strike>" + plainText + "</strike></html>");
            } else {
                describeLabel.setFont(describeLabel.getFont().deriveFont(Font.PLAIN));
                describeLabel.setForeground(Color.BLACK);
                String plainText = describeLabel.getText().replaceAll("<.*?>", "");
                describeLabel.setText(plainText);
            }
            
            refreshMainWindow(); // Gọi refresh sau khi thay đổi trạng thái
        }
    }
     
// CÁC PHƯƠNG THỨC SỰ KIỆN VỚI THAM SỐ TASK ID
    private void detailTask_JBTActionPerformed(ActionEvent evt, int taskId) {
        System.out.println("View task: " + taskId);     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFormDetailTask(taskId).setVisible(true);
            }
        });
    }
    
    private void editTask_JBTActionPerformed(ActionEvent evt, int taskId) {
        System.out.println("Edit task: " + taskId);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Truyền callback refresh vào form edit task
                new viewFormEditTask(taskId, new Runnable() {
                    @Override
                    public void run() {
                        refreshMainWindow();
                    }
                }).setVisible(true);
            }
        });      
    }
    
    private void deleteTask_JBTActionPerformed(ActionEvent evt, int taskId) {
        System.out.println("Delete task: " + taskId);
        // Xác nhận xóa
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn xóa task này?", "Xác nhận xóa", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            // Xóa task từ database
            if (controller.deleteTask(taskId)) {
                // SỬA LỖI: Gọi refreshMainWindow() thay vì refreshTaskList()
                refreshMainWindow();
                JOptionPane.showMessageDialog(this, "Đã xóa task thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa task!");
            }
        }
    }
 
    // Variables declaration - do not modify                     
    private javax.swing.JButton ADD_TASK_JBT;
    private javax.swing.JPanel addTask_JLB;
    private javax.swing.JLabel addTask_JLP;
    private javax.swing.JPanel displayAddTask_JLB;
    private javax.swing.JPanel displayCRUD_JLP;
    private javax.swing.JPanel display_JLP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}