/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewMain;

import controller.TaskController;
import model.Task;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class viewFormEditTask extends javax.swing.JFrame {
    private TaskController taskController;
    private int taskId;
    private Task currentTask;
    private Runnable refreshCallback;

    // Constructor với callback
    public viewFormEditTask(int taskId, Runnable refreshCallback) {
        initComponents();
        taskController = new TaskController();
        this.taskId = taskId;
        this.refreshCallback = refreshCallback;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chỉnh Sửa Công Việc");
        loadTaskData();
    }

    // Constructor mặc định
    public viewFormEditTask(int taskId) {
        initComponents();
        taskController = new TaskController();
        this.taskId = taskId;
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chỉnh Sửa Công Việc");
        loadTaskData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatusTask_JBTG = new javax.swing.ButtonGroup();
        formEditTask_JP_P = new javax.swing.JPanel();
        formEditTask_JP_C = new javax.swing.JPanel();
        formEditTaskDetail_JLB = new javax.swing.JLabel();
        formEditTaskDeadline_JLB1 = new javax.swing.JLabel();
        formEditTaskDeadline_JLB2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fromAddTaskDetail_JTA = new javax.swing.JTextArea();
        formEditTaskDeadline_JTF = new javax.swing.JTextField();
        formEditTaskDeadline_JLB3 = new javax.swing.JLabel();
        formEditStatusTask_JLB = new javax.swing.JLabel();
        statuHoanthanhTask_JRBT = new javax.swing.JRadioButton();
        statusPendddingTask_JRBT = new javax.swing.JRadioButton();
        formEditTaskTitle_JLB4 = new javax.swing.JLabel();
        formEditTaskTitle_JTF1 = new javax.swing.JTextField();
        formEditTask_JLP = new javax.swing.JLabel();
        formEditTask_JBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setTitle("Chỉnh Sửa Công Việc");

        formEditTask_JP_P.setBackground(new java.awt.Color(204, 255, 255));

        formEditTask_JP_C.setBackground(new java.awt.Color(235, 255, 255));
        formEditTask_JP_C.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        formEditTaskDetail_JLB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditTaskDetail_JLB.setForeground(new java.awt.Color(153, 153, 153));
        formEditTaskDetail_JLB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formEditTaskDetail_JLB.setText("Mô tả công việc:");

        formEditTaskDeadline_JLB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditTaskDeadline_JLB1.setForeground(new java.awt.Color(153, 153, 153));
        formEditTaskDeadline_JLB1.setText("Ngày hoàn thành:");

        formEditTaskDeadline_JLB2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditTaskDeadline_JLB2.setForeground(new java.awt.Color(153, 153, 153));
        formEditTaskDeadline_JLB2.setText("(YYYY-MM-DD)");

        fromAddTaskDetail_JTA.setColumns(20);
        fromAddTaskDetail_JTA.setRows(3);
        jScrollPane2.setViewportView(fromAddTaskDetail_JTA);

        formEditTaskDeadline_JLB3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditTaskDeadline_JLB3.setForeground(new java.awt.Color(255, 153, 153));
        formEditTaskDeadline_JLB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formEditTaskDeadline_JLB3.setText("(nếu không nhập mặc định là hôm nay)");

        formEditStatusTask_JLB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditStatusTask_JLB.setForeground(new java.awt.Color(153, 153, 153));
        formEditStatusTask_JLB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formEditStatusTask_JLB.setText("Trạng thái công việc:");

        StatusTask_JBTG.add(statuHoanthanhTask_JRBT);
        statuHoanthanhTask_JRBT.setText("Đã hoàn thành");

        StatusTask_JBTG.add(statusPendddingTask_JRBT);
        statusPendddingTask_JRBT.setText("Chưa hoàn thành");

        formEditTaskTitle_JLB4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditTaskTitle_JLB4.setForeground(new java.awt.Color(153, 153, 153));
        formEditTaskTitle_JLB4.setText("Tiêu đề công việc:");

        javax.swing.GroupLayout formEditTask_JP_CLayout = new javax.swing.GroupLayout(formEditTask_JP_C);
        formEditTask_JP_C.setLayout(formEditTask_JP_CLayout);
        formEditTask_JP_CLayout.setHorizontalGroup(
            formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditTask_JP_CLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formEditTask_JP_CLayout.createSequentialGroup()
                        .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formEditTaskDetail_JLB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(formEditStatusTask_JLB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(formEditTaskDeadline_JLB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formEditTaskDeadline_JLB1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formEditTaskDeadline_JTF)
                            .addComponent(formEditTaskDeadline_JLB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(formEditTask_JP_CLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addComponent(statuHoanthanhTask_JRBT, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(statusPendddingTask_JRBT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(formEditTask_JP_CLayout.createSequentialGroup()
                        .addComponent(formEditTaskTitle_JLB4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(formEditTaskTitle_JTF1)))
                .addContainerGap())
        );
        formEditTask_JP_CLayout.setVerticalGroup(
            formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formEditTask_JP_CLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formEditTaskTitle_JTF1)
                    .addComponent(formEditTaskTitle_JLB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(formEditTaskDetail_JLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEditTaskDeadline_JLB1)
                    .addComponent(formEditTaskDeadline_JTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEditTaskDeadline_JLB2)
                    .addComponent(formEditTaskDeadline_JLB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formEditTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEditStatusTask_JLB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statuHoanthanhTask_JRBT)
                    .addComponent(statusPendddingTask_JRBT))
                .addGap(8, 8, 8))
        );

        formEditTask_JLP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formEditTask_JLP.setText("Chi tiết nội dung chỉnh sửa công việc");
        
        formEditTask_JBT.setBackground(new java.awt.Color(235, 255, 255));
        formEditTask_JBT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formEditTask_JBT.setForeground(new java.awt.Color(153, 153, 153));
        formEditTask_JBT.setText("HOÀN THÀNH EDIT");
        formEditTask_JBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formEditTask_JBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formEditTask_JP_PLayout = new javax.swing.GroupLayout(formEditTask_JP_P);
        formEditTask_JP_P.setLayout(formEditTask_JP_PLayout);
        formEditTask_JP_PLayout.setHorizontalGroup(
            formEditTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formEditTask_JP_PLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(formEditTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formEditTask_JP_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formEditTask_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formEditTask_JP_PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formEditTask_JBT)
                .addGap(183, 183, 183)
                )
        );
        formEditTask_JP_PLayout.setVerticalGroup(
            formEditTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formEditTask_JP_PLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(formEditTask_JLP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formEditTask_JP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formEditTask_JBT)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formEditTask_JP_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formEditTask_JP_P, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formEditTask_JBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formEditTask_JBTActionPerformed
        updateTaskToDatabase();
    }//GEN-LAST:event_formEditTask_JBTActionPerformed

    /**
     * Phương thức tải dữ liệu công việc từ database
     */
    private void loadTaskData() {
        try {
            // Lấy thông tin task từ database
            currentTask = taskController.getTaskById(taskId);
            
            if (currentTask != null) {
                // Hiển thị thông tin lên giao diện
                formEditTaskTitle_JTF1.setText(currentTask.getTitle());
                fromAddTaskDetail_JTA.setText(currentTask.getDescription());
                formEditTaskDeadline_JTF.setText(currentTask.getDeadline());
                
                // Set trạng thái
                if ("Completed".equalsIgnoreCase(currentTask.getStatus()) || 
                    "Đã hoàn thành".equalsIgnoreCase(currentTask.getStatus())) {
                    statuHoanthanhTask_JRBT.setSelected(true);
                } else {
                    statusPendddingTask_JRBT.setSelected(true);
                }
                
                setTitle("Chỉnh Sửa Công Việc: " + currentTask.getTitle());
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy công việc với ID: " + taskId, "Lỗi", JOptionPane.ERROR_MESSAGE);
                dispose(); // Đóng cửa sổ nếu không tìm thấy
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Phương thức cập nhật task vào database
     */
    private void updateTaskToDatabase() {
        try {
            // Validate dữ liệu
            String title = formEditTaskTitle_JTF1.getText().trim();
            if (title.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tiêu đề công việc!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String description = fromAddTaskDetail_JTA.getText().trim();
            String deadline = formEditTaskDeadline_JTF.getText().trim();
            
            // Xử lý deadline
            if (deadline.isEmpty()) {
                // Mặc định là hôm nay
                deadline = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            } else {
                // Validate định dạng date
                try {
                    LocalDate.parse(deadline, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                } catch (DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ! Vui lòng nhập theo định dạng YYYY-MM-DD", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            // Xác định trạng thái
            String status = statusPendddingTask_JRBT.isSelected() ? "Chưa hoàn thành" : "Đã hoàn thành";
            
            // Cập nhật thông tin task
            currentTask.setTitle(title);
            currentTask.setDescription(description);
            currentTask.setDeadline(deadline);
            currentTask.setStatus(status);
            
            // Gọi controller để cập nhật vào database
            boolean success = taskController.updateTask(currentTask);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Cập nhật công việc thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                
                // GỌI CALLBACK ĐỂ REFRESH CỬA SỔ CHÍNH
                if (refreshCallback != null) {
                    refreshCallback.run();
                }
                
                dispose(); // Đóng cửa sổ sau khi cập nhật thành công
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật công việc thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi hệ thống", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Set taskId và tải lại dữ liệu (dùng khi muốn thay đổi task hiển thị)
     * @param taskId ID của công việc mới
     */
    public void setTaskId(int taskId) {
        this.taskId = taskId;
        loadTaskData();
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup StatusTask_JBTG;
    private javax.swing.JLabel formEditStatusTask_JLB;
    private javax.swing.JLabel formEditTaskDeadline_JLB1;
    private javax.swing.JLabel formEditTaskDeadline_JLB2;
    private javax.swing.JLabel formEditTaskDeadline_JLB3;
    private javax.swing.JTextField formEditTaskDeadline_JTF;
    private javax.swing.JLabel formEditTaskDetail_JLB;
    private javax.swing.JLabel formEditTaskTitle_JLB4;
    private javax.swing.JTextField formEditTaskTitle_JTF1;
    private javax.swing.JButton formEditTask_JBT;
    private javax.swing.JLabel formEditTask_JLP;
    private javax.swing.JPanel formEditTask_JP_C;
    private javax.swing.JPanel formEditTask_JP_P;
    private javax.swing.JTextArea fromAddTaskDetail_JTA;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton statuHoanthanhTask_JRBT;
    private javax.swing.JRadioButton statusPendddingTask_JRBT;
    // End of variables declaration//GEN-END:variables
}