/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewMain;

import controller.TaskController;
import model.Task;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class viewFormAddTask extends javax.swing.JFrame {
    private TaskController taskController;
    private Runnable refreshCallback;

    // Constructor với callback
    public viewFormAddTask(Runnable refreshCallback) {
        initComponents();
        taskController = new TaskController();
        this.refreshCallback = refreshCallback;
        setLocationRelativeTo(null);
        setTitle("Thêm Công Việc Mới");
    }

    // Constructor mặc định
    public viewFormAddTask() {
        initComponents();
        taskController = new TaskController();
        setLocationRelativeTo(null);
        setTitle("Thêm Công Việc Mới");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formAddTask_JP_P = new javax.swing.JPanel();
        formAddTask_JP_C = new javax.swing.JPanel();
        fromAddTaskDetail_JLB = new javax.swing.JLabel();
        fromAddTaskDeadline_JLB1 = new javax.swing.JLabel();
        fromAddTaskDeadline_JLB2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fromAddTaskDetail_JTA = new javax.swing.JTextArea();
        fromAddTaskDeadline_JTF = new javax.swing.JTextField();
        fromAddTaskDeadline_JLB3 = new javax.swing.JLabel();
        fromAddTaskTittle_JLP = new javax.swing.JLabel();
        fromAddTaskTittle_JTF = new javax.swing.JTextField();
        btnAddTask = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setTitle("Thêm Công Việc Mới");

        formAddTask_JP_P.setBackground(new java.awt.Color(204, 255, 255));
        formAddTask_JP_P.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHI TIẾT NỘI DUNG CÔNG VIỆC", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(153, 153, 153))); // NOI18N

        formAddTask_JP_C.setBackground(new java.awt.Color(235, 255, 255));

        fromAddTaskDetail_JLB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromAddTaskDetail_JLB.setForeground(new java.awt.Color(153, 153, 153));
        fromAddTaskDetail_JLB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fromAddTaskDetail_JLB.setText("Mô tả công việc:");

        fromAddTaskDeadline_JLB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromAddTaskDeadline_JLB1.setForeground(new java.awt.Color(153, 153, 153));
        fromAddTaskDeadline_JLB1.setText("Ngày hoàn thành:");

        fromAddTaskDeadline_JLB2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromAddTaskDeadline_JLB2.setForeground(new java.awt.Color(153, 153, 153));
        fromAddTaskDeadline_JLB2.setText("(YYYY-MM-DD)");

        fromAddTaskDetail_JTA.setColumns(20);
        fromAddTaskDetail_JTA.setRows(3);
        jScrollPane2.setViewportView(fromAddTaskDetail_JTA);

        fromAddTaskDeadline_JLB3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromAddTaskDeadline_JLB3.setForeground(new java.awt.Color(255, 102, 102));
        fromAddTaskDeadline_JLB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fromAddTaskDeadline_JLB3.setText("(nếu không nhập mặc định là hôm nay)");

        fromAddTaskTittle_JLP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fromAddTaskTittle_JLP.setForeground(new java.awt.Color(153, 153, 153));
        fromAddTaskTittle_JLP.setText("Tiêu đề:");

        javax.swing.GroupLayout formAddTask_JP_CLayout = new javax.swing.GroupLayout(formAddTask_JP_C);
        formAddTask_JP_C.setLayout(formAddTask_JP_CLayout);
        formAddTask_JP_CLayout.setHorizontalGroup(
            formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAddTask_JP_CLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromAddTaskTittle_JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromAddTaskDeadline_JLB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromAddTaskDeadline_JLB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromAddTaskDetail_JLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(fromAddTaskDeadline_JTF)
                    .addComponent(fromAddTaskDeadline_JLB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromAddTaskTittle_JTF))
                .addGap(35, 35, 35))
        );
        formAddTask_JP_CLayout.setVerticalGroup(
            formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAddTask_JP_CLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fromAddTaskTittle_JLP)
                    .addComponent(fromAddTaskTittle_JTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromAddTaskDetail_JLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromAddTaskDeadline_JLB1)
                    .addComponent(fromAddTaskDeadline_JTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formAddTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromAddTaskDeadline_JLB2)
                    .addComponent(fromAddTaskDeadline_JLB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        btnAddTask.setBackground(new java.awt.Color(231, 255, 255));
        btnAddTask.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTask.setForeground(new java.awt.Color(153, 153, 153));
        btnAddTask.setText("ADD TASK");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formAddTask_JP_PLayout = new javax.swing.GroupLayout(formAddTask_JP_P);
        formAddTask_JP_P.setLayout(formAddTask_JP_PLayout);
        formAddTask_JP_PLayout.setHorizontalGroup(
            formAddTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAddTask_JP_PLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(formAddTask_JP_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formAddTask_JP_PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent( btnAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        formAddTask_JP_PLayout.setVerticalGroup(
            formAddTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formAddTask_JP_PLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(formAddTask_JP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formAddTask_JP_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formAddTask_JP_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        addTaskToDatabase();
    }//GEN-LAST:event_btnAddTaskActionPerformed

    /**
     * Phương thức thêm task vào database
     */
    private void addTaskToDatabase() {
        try {
            // Lấy dữ liệu từ form
            String title = fromAddTaskTittle_JTF.getText().trim();
            String description = fromAddTaskDetail_JTA.getText().trim();
            String deadline = fromAddTaskDeadline_JTF.getText().trim();
            
            // Validate dữ liệu
            if (title.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tiêu đề công việc!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Xử lý deadline
            if (deadline.isEmpty()) {
                // Mặc định là hôm nay
                deadline = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            } else {
                // Validate định dạng date
                try {
                    LocalDate.parse(deadline, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                } catch (DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ! Vui lòng nhập theo định dạng YYYY-MM-DD", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            // Status mặc định là "Chưa hoàn thành"
            String status = "Chưa hoàn thành";
            
            // Tạo đối tượng Task
            Task newTask = new Task();
            newTask.setTitle(title);
            newTask.setDescription(description);
            newTask.setDeadline(deadline);
            newTask.setStatus(status);
            
            // Gọi controller để thêm vào database
            boolean success = taskController.addTask(newTask);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Thêm công việc thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                
                // GỌI CALLBACK ĐỂ REFRESH CỬA SỔ CHÍNH
                if (refreshCallback != null) {
                    refreshCallback.run();
                }
                
                clearForm();
                dispose(); // Đóng cửa sổ
            } else {
                JOptionPane.showMessageDialog(this, "Thêm công việc thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), "Lỗi hệ thống", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Xóa dữ liệu trên form sau khi thêm thành công
     */
    private void clearForm() {
        fromAddTaskTittle_JTF.setText("");
        fromAddTaskDetail_JTA.setText("");
        fromAddTaskDeadline_JTF.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JPanel formAddTask_JP_C;
    private javax.swing.JPanel formAddTask_JP_P;
    private javax.swing.JLabel fromAddTaskDeadline_JLB1;
    private javax.swing.JLabel fromAddTaskDeadline_JLB2;
    private javax.swing.JLabel fromAddTaskDeadline_JLB3;
    private javax.swing.JTextField fromAddTaskDeadline_JTF;
    private javax.swing.JLabel fromAddTaskDetail_JLB;
    private javax.swing.JTextArea fromAddTaskDetail_JTA;
    private javax.swing.JLabel fromAddTaskTittle_JLP;
    private javax.swing.JTextField fromAddTaskTittle_JTF;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}