/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.viewMain;

import controller.TaskController;
import model.Task;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class viewFormDetailTask extends javax.swing.JFrame {
    private TaskController taskController;
    private int taskId;

    /**
     * Constructor với taskId để hiển thị thông tin công việc
     * @param taskId ID của công việc cần hiển thị
     */
    public viewFormDetailTask(int taskId) {
        initComponents();
        taskController = new TaskController();
        this.taskId = taskId;
        setLocationRelativeTo(null);// Hiển thị giữa màn hình
        setTitle("Chi Tiết Công Việc");
        loadTaskData(); // Tải dữ liệu khi khởi tạo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formDetailTask_JP_P = new javax.swing.JPanel();
        formDetailTask_JLP1 = new javax.swing.JLabel();
        formDetailTask_JLP2 = new javax.swing.JLabel();
        formDetailTask_JP_C = new javax.swing.JPanel();
        formDetailTaskDetail_JLP1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        formDetailTaskDeadline_JLP2 = new javax.swing.JLabel();
        formDetailTaskStatus_JLP1 = new javax.swing.JLabel();
        formDetailTaskDeadline_JLP1 = new javax.swing.JLabel();
        formDetailTaskStatus_JLP2 = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi Tiết Công Việc");

        formDetailTask_JP_P.setBackground(new java.awt.Color(204, 255, 255));

        formDetailTask_JLP1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        formDetailTask_JLP1.setForeground(new java.awt.Color(153, 153, 153));
        formDetailTask_JLP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        formDetailTask_JLP1.setText("Thông tin của công việc:");

        formDetailTask_JLP2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        formDetailTask_JLP2.setForeground(new java.awt.Color(0, 51, 153));
        formDetailTask_JLP2.setText("Tên công việc");

        formDetailTask_JP_C.setBackground(new java.awt.Color(235, 255, 255));
        formDetailTask_JP_C.setBorder(javax.swing.BorderFactory.createTitledBorder(null,"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 153)));

        formDetailTaskDetail_JLP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formDetailTaskDetail_JLP1.setForeground(new java.awt.Color(153, 153, 153));
        formDetailTaskDetail_JLP1.setText("Mô tả công việc:");

        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jScrollPane3.setViewportView(jLabel6);

        formDetailTaskDeadline_JLP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formDetailTaskDeadline_JLP2.setForeground(new java.awt.Color(153, 153, 153));
        formDetailTaskDeadline_JLP2.setText("Ngày hoàn thành:");

        formDetailTaskStatus_JLP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formDetailTaskStatus_JLP1.setForeground(new java.awt.Color(255, 102, 0));
        formDetailTaskStatus_JLP1.setText("2024-01-01");

        formDetailTaskDeadline_JLP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formDetailTaskDeadline_JLP1.setForeground(new java.awt.Color(153, 153, 153));
        formDetailTaskDeadline_JLP1.setText("Trạng thái:");

        formDetailTaskStatus_JLP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        formDetailTaskStatus_JLP2.setForeground(new java.awt.Color(0, 102, 255));
        formDetailTaskStatus_JLP2.setText("Chưa hoàn thành");

        javax.swing.GroupLayout formDetailTask_JP_CLayout = new javax.swing.GroupLayout(formDetailTask_JP_C);
        formDetailTask_JP_C.setLayout(formDetailTask_JP_CLayout);
        formDetailTask_JP_CLayout.setHorizontalGroup(
            formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDetailTask_JP_CLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formDetailTaskDeadline_JLP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formDetailTaskDeadline_JLP2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(formDetailTaskDetail_JLP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formDetailTask_JP_CLayout.createSequentialGroup()
                        .addComponent(formDetailTaskStatus_JLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDetailTask_JP_CLayout.createSequentialGroup()
                        .addGroup(formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(formDetailTaskStatus_JLP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(29, 29, 29))))
        );
        formDetailTask_JP_CLayout.setVerticalGroup(
            formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDetailTask_JP_CLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formDetailTaskDetail_JLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDetailTaskDeadline_JLP2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formDetailTaskStatus_JLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formDetailTask_JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDetailTaskDeadline_JLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formDetailTaskStatus_JLP2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        

        javax.swing.GroupLayout formDetailTask_JP_PLayout = new javax.swing.GroupLayout(formDetailTask_JP_P);
        formDetailTask_JP_P.setLayout(formDetailTask_JP_PLayout);
        formDetailTask_JP_PLayout.setHorizontalGroup(
            formDetailTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDetailTask_JP_PLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(formDetailTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formDetailTask_JP_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formDetailTask_JP_PLayout.createSequentialGroup()
                        .addComponent(formDetailTask_JLP1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDetailTask_JLP2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        ))
                .addGap(14, 14, 14))
        );
        formDetailTask_JP_PLayout.setVerticalGroup(
            formDetailTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDetailTask_JP_PLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(formDetailTask_JP_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDetailTask_JLP1)
                    .addComponent(formDetailTask_JLP2)
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formDetailTask_JP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDetailTask_JP_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDetailTask_JP_P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose(); // Đóng cửa sổ
    }                                        

    /**
     * Phương thức tải dữ liệu công việc từ database
     */
    private void loadTaskData() {
        try {
            // Lấy thông tin task từ database
            Task task = taskController.getTaskById(taskId);
            
            if (task != null) {
                // Hiển thị thông tin lên giao diện:
                formDetailTask_JLP2.setText(task.getTitle()); // Hiển thị title
                jLabel6.setText("<html>" + (task.getDescription() != null ? task.getDescription() : "Không có mô tả") + "</html>"); // Hiển thị description
                formDetailTaskStatus_JLP1.setText(task.getDeadline() != null ? task.getDeadline() : "Không có"); // Hiển thị deadline
                formDetailTaskStatus_JLP2.setText(task.getStatus() != null ? task.getStatus() : "Không xác định"); // Hiển thị status
                
                // Đổi màu trạng thái
                setStatusColor(task.getStatus());
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Không tìm thấy công việc với ID: " + taskId, 
                    "Lỗi", 
                    JOptionPane.ERROR_MESSAGE);
                dispose(); // Đóng cửa sổ nếu không tìm thấy
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Lỗi khi tải dữ liệu: " + e.getMessage(), 
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    /**
     * Đặt màu cho trạng thái công việc
     * @param status Trạng thái công việc
     */
    private void setStatusColor(String status) {
        if (status == null) return;
        
        switch (status.toLowerCase()) {
            case "đã hoàn thành":
            case "completed":
                formDetailTaskStatus_JLP2.setForeground(new java.awt.Color(0, 153, 0)); // Xanh lá - Đã hoàn thành
                break;
            case "chưa hoàn thành":
            case "pending":
                formDetailTaskStatus_JLP2.setForeground(new java.awt.Color(0, 102, 255)); // Xanh dương - Chưa hoàn thành
                break;
            case "đang thực hiện":
            case "in progress":
                formDetailTaskStatus_JLP2.setForeground(new java.awt.Color(255, 153, 0)); // Cam - Đang thực hiện
                break;
            default:
                formDetailTaskStatus_JLP2.setForeground(new java.awt.Color(153, 153, 153)); // Xám - Không xác định
                break;
        }
    }
    
    /**
     * Set taskId và tải lại dữ liệu (dùng khi muốn thay đổi task hiển thị)
     * @param taskId ID của công việc mới
     */
    public void setTaskId(int taskId) {
        this.taskId = taskId;
        loadTaskData();
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    
    private javax.swing.JLabel formDetailTaskDeadline_JLP1;
    private javax.swing.JLabel formDetailTaskDeadline_JLP2;
    private javax.swing.JLabel formDetailTaskDetail_JLP1;
    private javax.swing.JLabel formDetailTaskStatus_JLP1;
    private javax.swing.JLabel formDetailTaskStatus_JLP2;
    private javax.swing.JLabel formDetailTask_JLP1;
    private javax.swing.JLabel formDetailTask_JLP2;
    private javax.swing.JPanel formDetailTask_JP_C;
    private javax.swing.JPanel formDetailTask_JP_P;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}